#!/usr/bin/env python3
"""Build .gitignore from upstream github/gitignore templates plus every .gitignore.d fragment.

    fold_gitignore.py <dest> [extra-template-sources]

The upstream templates cover the bulk per language, and which languages rendered
is read from the tree itself: each language recipe writes a marker file, and the
table below maps markers to templates. The argument carries additions only. A
fragment carries what a template cannot express: `Cargo.lock` ignored for a
library but committed for a binary, `vendor/` under Go vendor mode, or a tool's
output path.

Always ignored regardless of language, because a layer or a hook writes them:
the repomix pack, generated skill directories, and the beads Dolt database.

Idempotent: the whole file is rebuilt from its sources every run.

Templates are fetched through `gh api` from the github/gitignore repository --
`gh` is already required for the repository creation the interview offers, so
this adds no binary. The fetch is retried: one render failed under
`pytest -n auto` while the same command succeeded on a rerun and across twelve
concurrent renders, which is a transient fetch rather than a systematic one.
"""

from __future__ import annotations

import os
import shutil
import subprocess
import sys
import time
from pathlib import Path

FETCH_TIMEOUT_SECONDS = 120

# Five attempts with exponential backoff, so the waits are 2, 4, 8, and 16 seconds and a render
# survives roughly half a minute of upstream trouble.
#
# Sized against a real outage rather than guessed. `raw.githubusercontent.com` returned 429 and
# then 503 for the gitignore templates, verified with curl: three attempts over six seconds
# failed thirteen tests. The API route `gh api` takes is authenticated, which is what keeps it
# clear of the anonymous rate limit that outage hit.
#
# It does not survive a sustained outage, and it is not meant to. The alternative was vendoring
# the three OS templates, which trades an upstream dependency for three files to keep current.
FETCH_ATTEMPTS = 5
# Overridable so a test exercising the give-up path does not spend thirty seconds sleeping. Not a
# knob for a person to turn: the default is the measured one.
FETCH_BACKOFF_SECONDS = float(os.environ.get("GITIGNORE_FETCH_BACKOFF_SECONDS", "2"))

# The operating system writes these whatever the project is, so they are added for
# every render rather than derived from the language layers. Finder writes a
# `.DS_Store` into any directory it displays, and one reached a template directory
# in this repository.
#
# github/gitignore carries them, so nothing here is hand-rolled: `Global/macOS` covers
# `.DS_Store` and the `._*` resource forks, `Global/Windows` covers `Thumbs.db` and
# `desktop.ini`, `Global/Linux` covers `*~` and the trash directories.
#
# Editor directories are deliberately absent. `.vscode/` and `.idea/` follow the
# developer rather than the project, so they belong in a global `core.excludesFile`
# rather than in every repository this scaffolds.
OS_TEMPLATES = ("gh:Global/macOS", "gh:Global/Windows", "gh:Global/Linux")

# Which languages rendered, read from the tree rather than from an answer the
# agent had to assemble: each language recipe writes its marker unconditionally,
# and a recipe whose files were removed by hand stops contributing. Same
# detection stance as agentic/marketplace's recommend.py.
#
# iac/terraform is deliberately absent: its fragment carries the whole set,
# because the upstream Terraform template predates .tofu files.
LANGUAGE_MARKERS = (
    ("rust-toolchain.toml", "gh:Rust"),
    ("ruff.toml", "gh:Python"),
    (".golangci.yml", "gh:Go"),
    ("biome.json", "gh:Node"),
)

# Written by a hook or a layer rather than by a person, and large.
ALWAYS = """# Generated by a tool in this repository, never committed.
repomix.xml
repomix-*.xml
.claude/skills/repomix-*/

# Local state
*.log
"""


def template_path(source: str) -> str:
    """`gh:Global/macOS` -> `Global/macOS.gitignore` in github/gitignore."""
    return f"{source.removeprefix('gh:')}.gitignore"


def fetch_template(source: str) -> str:
    """One template through `gh api`, retried.

    Bytes, not text. `text=True` enables universal newlines, which rewrites a lone
    CR to LF, and GitHub's macOS template carries two patterns holding a literal CR:
    `Icon[\\r]` and `.HFS+ Private Directory Data[\\r]`. Converting it splits each
    across two lines, leaving `Icon[` behind, which is an unterminated character
    class. Every tool reading the file then errors on it, zizmor among them.
    """
    command = [
        "gh",
        "api",
        "-H",
        "Accept: application/vnd.github.raw",
        f"repos/github/gitignore/contents/{template_path(source)}",
    ]
    detail = ""
    for attempt in range(1, FETCH_ATTEMPTS + 1):
        try:
            result = subprocess.run(
                command,
                capture_output=True,
                check=False,
                timeout=FETCH_TIMEOUT_SECONDS,
            )
        except subprocess.TimeoutExpired:
            detail = f"timed out after {FETCH_TIMEOUT_SECONDS}s"
        else:
            if result.returncode == 0:
                return result.stdout.decode(errors="replace")
            detail = result.stderr.decode(errors="replace").strip() or f"exit {result.returncode}"

        if attempt < FETCH_ATTEMPTS:
            # Said out loud. A silent retry turns a systematic failure into a slow render
            # nobody investigates.
            print(
                f"gh api attempt {attempt} of {FETCH_ATTEMPTS} failed for {source} "
                f"({detail}), retrying",
                file=sys.stderr,
            )
            time.sleep(FETCH_BACKOFF_SECONDS * 2 ** (attempt - 1))

    raise SystemExit(f"gh api failed for {source} after {FETCH_ATTEMPTS} attempts: {detail}")


def templates_output(sources: list[str]) -> str:
    if not sources:
        return ""
    if shutil.which("gh") is None:
        print("gh absent from PATH, skipping the upstream templates", file=sys.stderr)
        return ""
    blocks = []
    for source in sources:
        blocks.append(f"# {source}\n{fetch_template(source).strip()}\n")
    return "\n".join(blocks)


def fragments(dest: Path) -> str:
    """Fold .gitignore.d/* in name order so two runs produce the same file."""
    directory = dest / ".gitignore.d"
    if not directory.is_dir():
        return ""
    blocks = []
    for fragment in sorted(directory.iterdir()):
        if not fragment.is_file() or fragment.name.startswith("."):
            continue
        body = fragment.read_text().strip()
        if not body:
            continue
        # A fragment may open with its own comment; do not add a second one.
        header = "" if body.startswith("#") else f"# {fragment.name}\n"
        blocks.append(f"{header}{body}\n")
    return "\n".join(blocks)


def detected_templates(dest: Path) -> list[str]:
    """The templates the tree itself asks for, root and member directories both.

    A profile render leaves the marker at the root; `just add <member>` renders a
    language recipe at the member path, where the tool configs deliberately stay
    (they describe that package). Depth two covers `crates/*` and `packages/*`
    without walking dependency trees, and ignored directories are skipped by name
    rather than by consulting the very file this run is rebuilding.
    """
    skip = {".git", "node_modules", "target", ".venv", "vendor", "dist", "build"}
    found = []
    for marker, template in LANGUAGE_MARKERS:
        hits = [dest / marker]
        hits += [d / marker for d in dest.iterdir() if d.is_dir() and d.name not in skip]
        hits += [
            m / marker
            for d in dest.iterdir()
            if d.is_dir() and d.name not in skip
            for m in d.iterdir()
            if m.is_dir() and m.name not in skip
        ]
        if any(h.is_file() for h in hits):
            found.append(template)
    return found


def main() -> int:
    if len(sys.argv) < 2:
        print(__doc__, file=sys.stderr)
        return 2

    dest = Path(sys.argv[1])
    extra = sys.argv[2].split() if len(sys.argv) > 2 and sys.argv[2].strip() else []

    # The OS templates are unconditional; the rest are read from the tree, with
    # the answer carrying additions only. Ordered so a language rule reads before
    # the OS noise, and de-duplicated in case a caller passes one explicitly.
    sources = list(dict.fromkeys([*detected_templates(dest), *extra, *OS_TEMPLATES]))

    parts = [ALWAYS]

    fragment_text = fragments(dest)
    if fragment_text:
        parts.append(fragment_text)

    remote = templates_output(sources)
    if remote:
        parts.append(remote)

    (dest / ".gitignore").write_text("\n".join(part.rstrip() + "\n" for part in parts if part))

    counted = (
        len(list((dest / ".gitignore.d").iterdir())) if (dest / ".gitignore.d").is_dir() else 0
    )
    print(f".gitignore written from {len(sources)} upstream template(s) and {counted} fragment(s)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
