#!/usr/bin/env python3
"""Build .gitignore from gitnr templates plus every .gitignore.d fragment.

    fold_gitignore.py <dest> [gitnr-sources]

gitnr covers the bulk per language. A fragment carries what gitnr cannot express:
`Cargo.lock` ignored for a library but committed for a binary, `vendor/` under Go
vendor mode, or a tool's output path.

Always ignored regardless of language, because a layer or a hook writes them:
the repomix pack, generated skill directories, and the beads Dolt database.

Idempotent: the whole file is rebuilt from its sources every run.

gitnr fetches its templates over the network, so the fetch is retried. It failed once under
`pytest -n auto` while the same command succeeded on a rerun and across twelve concurrent
renders, which is a transient fetch rather than a systematic one.
"""

from __future__ import annotations

import os
import shutil
import subprocess
import sys
import time
from pathlib import Path

GITNR_TIMEOUT_SECONDS = 120

# Five attempts with exponential backoff, so the waits are 2, 4, 8, and 16 seconds and a render
# survives roughly half a minute of upstream trouble.
#
# Sized against a real outage rather than guessed. `raw.githubusercontent.com` returned 429 and
# then 503 for the gitignore templates, verified with curl: three attempts over six seconds
# failed thirteen tests, and `Global/macOS` passed only because gitnr still had it cached from an
# earlier run. A template is cached for an hour, so a successful attempt makes the next render
# local and the backoff costs nothing on a normal day.
#
# It does not survive a sustained outage, and it is not meant to. The alternative was vendoring
# the three OS templates, which trades an upstream dependency for three files to keep current.
GITNR_ATTEMPTS = 5
# Overridable so a test exercising the give-up path does not spend thirty seconds sleeping. Not a
# knob for a person to turn: the default is the measured one.
GITNR_BACKOFF_SECONDS = float(os.environ.get("GITNR_BACKOFF_SECONDS", "2"))

# The operating system writes these whatever the project is, so they are added for
# every render rather than derived from the language layers. Finder writes a
# `.DS_Store` into any directory it displays, and one reached a template directory
# in this repository.
#
# gitnr carries them, so nothing here is hand-rolled: `Global/macOS` covers
# `.DS_Store` and the `._*` resource forks, `Global/Windows` covers `Thumbs.db` and
# `desktop.ini`, `Global/Linux` covers `*~` and the trash directories.
#
# Editor directories are deliberately absent. `.vscode/` and `.idea/` follow the
# developer rather than the project, so they belong in a global `core.excludesFile`
# rather than in every repository this scaffolds.
OS_TEMPLATES = ("gh:Global/macOS", "gh:Global/Windows", "gh:Global/Linux")

# Written by a hook or a layer rather than by a person, and large.
ALWAYS = """# Generated by a tool in this repository, never committed.
repomix.xml
repomix-*.xml
.claude/skills/repomix-*/

# Local state
*.log
"""


def gitnr_output(sources: list[str]) -> str:
    if not sources:
        return ""
    if shutil.which("gitnr") is None:
        print("gitnr absent from PATH, skipping its templates", file=sys.stderr)
        return ""
    # Bytes, not text. `text=True` enables universal newlines, which rewrites a lone
    # CR to LF, and GitHub's macOS template carries two patterns holding a literal CR:
    # `Icon[\r]` and `.HFS+ Private Directory Data[\r]`. Converting it splits each
    # across two lines, leaving `Icon[` behind, which is an unterminated character
    # class. Every tool reading the file then errors on it, zizmor among them.
    # Retried, because the fetch is the failure. gitnr caches a template for an hour, so a cold
    # cache is the only time this touches the network, and that is when it broke: one render
    # exited non-zero under `pytest -n auto` while the same command succeeded on a rerun and
    # across twelve concurrent renders. A warm cache makes the second attempt local, so the
    # backoff exists for the case where the cache is cold for every attempt.
    detail = ""
    for attempt in range(1, GITNR_ATTEMPTS + 1):
        try:
            result = subprocess.run(
                ["gitnr", "create", *sources],
                capture_output=True,
                check=False,
                timeout=GITNR_TIMEOUT_SECONDS,
            )
        except subprocess.TimeoutExpired:
            detail = f"timed out after {GITNR_TIMEOUT_SECONDS}s"
        else:
            if result.returncode == 0:
                return result.stdout.decode(errors="replace")
            detail = result.stderr.decode(errors="replace").strip() or f"exit {result.returncode}"

        if attempt < GITNR_ATTEMPTS:
            # Said out loud. A silent retry turns a systematic failure into a slow render
            # nobody investigates.
            print(
                f"gitnr attempt {attempt} of {GITNR_ATTEMPTS} failed ({detail}), retrying",
                file=sys.stderr,
            )
            time.sleep(GITNR_BACKOFF_SECONDS * 2 ** (attempt - 1))

    raise SystemExit(
        f"gitnr failed for {' '.join(sources)} after {GITNR_ATTEMPTS} attempts: {detail}"
    )


def fragments(dest: Path) -> str:
    """Fold .gitignore.d/* in name order so two runs produce the same file."""
    directory = dest / ".gitignore.d"
    if not directory.is_dir():
        return ""
    blocks = []
    for fragment in sorted(directory.iterdir()):
        if not fragment.is_file() or fragment.name.startswith("."):
            continue
        body = fragment.read_text().strip()
        if not body:
            continue
        # A fragment may open with its own comment; do not add a second one.
        header = "" if body.startswith("#") else f"# {fragment.name}\n"
        blocks.append(f"{header}{body}\n")
    return "\n".join(blocks)


def main() -> int:
    if len(sys.argv) < 2:
        print(__doc__, file=sys.stderr)
        return 2

    dest = Path(sys.argv[1])
    derived = sys.argv[2].split() if len(sys.argv) > 2 and sys.argv[2].strip() else []

    # The OS templates are unconditional; the rest follow from which language
    # layers rendered. Ordered so a language rule reads before the OS noise, and
    # de-duplicated in case a caller passes one explicitly.
    sources = list(dict.fromkeys([*derived, *OS_TEMPLATES]))

    parts = [ALWAYS]

    fragment_text = fragments(dest)
    if fragment_text:
        parts.append(fragment_text)

    remote = gitnr_output(sources)
    if remote:
        parts.append(remote)

    (dest / ".gitignore").write_text("\n".join(part.rstrip() + "\n" for part in parts if part))

    counted = (
        len(list((dest / ".gitignore.d").iterdir())) if (dest / ".gitignore.d").is_dir() else 0
    )
    print(f".gitignore written from {len(sources)} gitnr source(s) and {counted} fragment(s)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
