"""quality/hooks: the root config, the repo-wide checks, and the fragment merge."""

from __future__ import annotations

import shutil
import subprocess
import sys
from pathlib import Path

import pytest
import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
RENDER = REPO_ROOT / "scripts" / "render.py"
MERGE = REPO_ROOT / "templates" / "quality" / "hooks" / "template" / "scripts" / "merge_hooks.py"

ANSWERS = """\
hook_exclude_patterns: []
max_file_kb: 500
commit_scopes: []
"""


def render(layer: str, dest: Path, answers: str) -> subprocess.CompletedProcess[str]:
    answers_file = dest.parent / f"{dest.name}-answers.yml"
    answers_file.write_text(answers)
    return subprocess.run(
        [sys.executable, str(RENDER), layer, str(dest), "--answers", str(answers_file)],
        capture_output=True,
        text=True,
        check=False,
    )


def merge(dest: Path) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        [sys.executable, str(MERGE), str(dest)],
        capture_output=True,
        text=True,
        check=False,
    )


@pytest.fixture
def rendered(tmp_path: Path) -> Path:
    dest = tmp_path / "d"
    dest.mkdir()
    subprocess.run(["git", "init", "-q", str(dest)], check=True)
    result = render("quality/hooks", dest, ANSWERS)
    assert result.returncode == 0, result.stderr
    return dest


def config(dest: Path) -> dict:
    return yaml.safe_load((dest / ".pre-commit-config.yaml").read_text())


def hook_ids(dest: Path) -> list[str]:
    return [h["id"] for r in config(dest)["repos"] for h in r["hooks"]]


# --- the generated root config --------------------------------------------


def test_the_layer_generates_the_root_config(rendered: Path) -> None:
    """prek reads one file and has no include directive, so the merge is the layer."""
    assert (rendered / ".pre-commit-config.yaml").is_file()
    assert (rendered / ".pre-commit.d" / "hygiene.yaml").is_file()
    assert (rendered / ".pre-commit.d" / "beads.yaml").is_file()


def test_every_declared_stage_reaches_default_install_hook_types(rendered: Path) -> None:
    """`prek install` writes one shim per entry, so a missing stage is a dead hook.

    This is the merge's whole reason for computing the list rather than hardcoding
    it: a fragment declaring `stages: [pre-push]` gets no pre-push shim otherwise,
    and nothing reports that the hook never fires.
    """
    spec = config(rendered)
    declared = {
        stage
        for repo in spec["repos"]
        for hook in repo["hooks"]
        for stage in hook.get("stages", ["pre-commit"])
    }
    assert declared <= set(spec["default_install_hook_types"]), (
        "a hook declares a stage that install would write no shim for"
    )


def test_the_config_says_it_is_generated(rendered: Path) -> None:
    """Editing it is lost work, so the file has to say where to edit instead."""
    body = (rendered / ".pre-commit-config.yaml").read_text()
    assert "generated from .pre-commit.d/" in body
    assert "Do not edit this file" in body


def test_a_command_entry_is_not_line_wrapped(rendered: Path) -> None:
    """A wrapped entry still folds back to the same command, but reads as broken.

    It also rewraps on every later edit, which turns a one-line change into a
    reformatted block. Checked by finding each entry's value in the raw text: a
    wrapped scalar is split across lines, so the whole string appears nowhere.
    """
    raw = (rendered / ".pre-commit-config.yaml").read_text()
    entries = [
        hook["entry"]
        for repo in config(rendered)["repos"]
        for hook in repo["hooks"]
        if hook.get("entry")
    ]
    assert entries, "no entries to check, so this test proves nothing"

    for entry in entries:
        # The longest entries are the bd guards, and those are the ones that wrapped.
        assert entry in raw, f"entry is wrapped across lines: {entry!r}"


# --- the checks themselves -------------------------------------------------


def test_the_repo_wide_checks_are_present(rendered: Path) -> None:
    ids = hook_ids(rendered)
    for expected in (
        "trailing-whitespace",
        "check-added-large-files",
        "detect-private-key",
        "betterleaks-system",
        "typos",
        "shellcheck",
        "conventional-pre-commit",
        "trufflehog",
        "actionlint",
        "zizmor",
        "taplo",
        "lychee",
    ):
        assert expected in ids, f"{expected} is absent"


def test_no_language_hook_lives_in_this_layer(rendered: Path) -> None:
    """Each lang/* layer owns its own fragment, so hooks travel with the language."""
    ids = hook_ids(rendered)
    for language_hook in ("cargo-fmt", "ruff-format", "go-fmt", "biome", "ty", "tsc"):
        assert language_hook not in ids, f"{language_hook} belongs to a lang/* layer"


def test_the_slow_checks_stay_in_ci(rendered: Path) -> None:
    """Measured on a 212-file repo: cspell 1.7s, markdownlint 1.2s, pinact 1.4s.

    They run in the quality workflow instead, so a commit does not wait on them.
    """
    ids = hook_ids(rendered)
    for slow in ("cspell", "markdownlint", "yamllint", "pinact"):
        assert slow not in ids, f"{slow} is too slow for a commit hook"


def test_the_offline_variants_are_used_where_a_commit_would_wait(rendered: Path) -> None:
    """A commit must not block on HTTP. CI runs both without the offline flag."""
    entries = {h["id"]: h.get("entry", "") for r in config(rendered)["repos"] for h in r["hooks"]}
    assert "--offline" in entries["lychee"]
    assert "--offline" in entries["zizmor"]


def test_the_large_file_threshold_is_threaded(tmp_path: Path) -> None:
    dest = tmp_path / "d"
    dest.mkdir()
    render("quality/hooks", dest, ANSWERS.replace("max_file_kb: 500", "max_file_kb: 42"))
    args = next(
        h["args"]
        for r in config(dest)["repos"]
        for h in r["hooks"]
        if h["id"] == "check-added-large-files"
    )
    assert "--maxkb=42" in args


# --- conventional commits --------------------------------------------------


def conventional_args(dest: Path) -> list[str]:
    return next(
        h.get("args", [])
        for r in config(dest)["repos"]
        for h in r["hooks"]
        if h["id"] == "conventional-pre-commit"
    )


def test_the_commit_message_check_runs_at_the_commit_msg_stage(rendered: Path) -> None:
    """At pre-commit there is no message yet, so the stage is the whole hook."""
    stages = next(
        h["stages"]
        for r in config(rendered)["repos"]
        for h in r["hooks"]
        if h["id"] == "conventional-pre-commit"
    )
    assert stages == ["commit-msg"]
    assert "commit-msg" in config(rendered)["default_install_hook_types"]


def test_no_scope_allowlist_means_no_force_scope(rendered: Path) -> None:
    """`--force-scope` without `--scopes` demands a scope while accepting any."""
    args = conventional_args(rendered)
    assert "--strict" in args
    assert "--force-scope" not in args


def test_a_scope_allowlist_forces_and_lists_the_scopes(tmp_path: Path) -> None:
    dest = tmp_path / "d"
    dest.mkdir()
    render(
        "quality/hooks",
        dest,
        ANSWERS.replace("commit_scopes: []", 'commit_scopes: ["host", "lang"]'),
    )
    args = conventional_args(dest)
    assert "--force-scope" in args
    assert "--scopes" in args
    assert "host,lang" in args


# --- beads hooks -----------------------------------------------------------


def test_bd_gets_one_prek_entry_per_git_hook(rendered: Path) -> None:
    """Five prek entries replace the shims `bd init` would install.

    `bd init --skip-hooks` avoids the copy that also picked up ambient hook
    binaries, which is how an unusable 347MB git-defender hook blocked every commit.
    """
    ids = hook_ids(rendered)
    for event in (
        "pre-commit",
        "prepare-commit-msg",
        "post-checkout",
        "post-merge",
        "pre-push",
    ):
        assert f"bd-{event}" in ids, f"no prek entry for bd's {event} hook"
        assert event in config(rendered)["default_install_hook_types"]


def test_a_bd_entry_is_guarded_so_a_clone_without_bd_still_commits(rendered: Path) -> None:
    """beads is optional tooling. Without the guard every commit fails for anyone
    who does not have bd installed.

    The guard lives wherever the entry does: inline for the five event shims, and inside
    the script for the database push, whose message has quoting an inline entry cannot
    carry.
    """
    for repo in config(rendered)["repos"]:
        for hook in repo["hooks"]:
            if not hook["id"].startswith("bd-"):
                continue

            entry = hook["entry"]
            if "bd-dolt-push.sh" in entry:
                # agentic/beads ships that script and guards on bd inside it. This
                # layer renders whether or not beads did, so the entry guards on the
                # script being there at all.
                assert "test -x" in entry, f"{hook['id']} runs a script that may be absent"
                continue

            assert "command -v bd" in entry, f"{hook['id']} is unguarded"
            # Forwards git's own hook arguments; prepare-commit-msg needs them.
            assert '"$@"' in entry


# --- the merge -------------------------------------------------------------


def test_the_merge_folds_a_language_fragment(tmp_path: Path) -> None:
    """A lang/* layer's hooks reach the root config without this layer changing."""
    dest = tmp_path / "d"
    dest.mkdir()
    subprocess.run(["git", "init", "-q", str(dest)], check=True)
    render("quality/hooks", dest, ANSWERS)
    before = len(hook_ids(dest))

    (dest / ".pre-commit.d" / "probe.yaml").write_text(
        "repos:\n"
        "  - repo: local\n"
        "    hooks:\n"
        "      - id: probe-fmt\n"
        "        name: probe\n"
        "        entry: true\n"
        "        language: system\n"
        "      - id: probe-lint\n"
        "        name: probe lint\n"
        "        entry: true\n"
        "        language: system\n"
        "        stages: [pre-push]\n"
    )
    result = merge(dest)

    assert result.returncode == 0, result.stderr
    ids = hook_ids(dest)
    assert "probe-fmt" in ids and "probe-lint" in ids
    assert len(ids) == before + 2
    # The new fragment introduced a stage, which install now writes a shim for.
    assert "pre-push" in config(dest)["default_install_hook_types"]


def test_the_merge_is_idempotent(rendered: Path) -> None:
    """Two runs produce the same bytes, so re-rendering never churns the file."""
    first = (rendered / ".pre-commit-config.yaml").read_text()
    assert merge(rendered).returncode == 0
    assert (rendered / ".pre-commit-config.yaml").read_text() == first


def test_every_fragment_exclude_survives_the_merge(tmp_path: Path) -> None:
    """Taking only the first would silently un-exclude what a later layer needed."""
    dest = tmp_path / "d"
    dest.mkdir()
    (dest / ".pre-commit.d").mkdir()
    (dest / ".pre-commit.d" / "a.yaml").write_text(
        'exclude: "^vendor/"\nrepos:\n  - repo: builtin\n    hooks:\n      - {id: check-yaml}\n'
    )
    (dest / ".pre-commit.d" / "b.yaml").write_text(
        'exclude: "^generated/"\nrepos:\n  - repo: builtin\n    hooks:\n      - {id: check-toml}\n'
    )

    assert merge(dest).returncode == 0

    exclude = config(dest)["exclude"]
    assert "vendor/" in exclude
    assert "generated/" in exclude


def test_a_rev_conflict_takes_the_higher_version_and_warns(tmp_path: Path) -> None:
    """Compared as versions, not strings: v1.10.0 is newer than v1.2.0."""
    dest = tmp_path / "d"
    dest.mkdir()
    (dest / ".pre-commit.d").mkdir()
    for name, rev in (("a.yaml", "v1.2.0"), ("b.yaml", "v1.10.0")):
        (dest / ".pre-commit.d" / name).write_text(
            f"repos:\n  - repo: https://example.com/x\n    rev: {rev}\n"
            f"    hooks:\n      - {{id: h-{name[0]}}}\n"
        )

    result = merge(dest)

    assert result.returncode == 0
    assert config(dest)["repos"][0]["rev"] == "v1.10.0"
    # A silent pick would leave a project on a version no fragment asked for.
    assert "v1.10.0" in result.stderr


def test_an_unknown_stage_fails_rather_than_writing_a_dead_hook(tmp_path: Path) -> None:
    """A typo would otherwise install no shim and report nothing at commit time."""
    dest = tmp_path / "d"
    dest.mkdir()
    (dest / ".pre-commit.d").mkdir()
    (dest / ".pre-commit.d" / "a.yaml").write_text(
        "repos:\n  - repo: local\n    hooks:\n      - id: x\n        name: x\n"
        "        entry: true\n        language: system\n        stages: [pre-comit]\n"
    )

    result = merge(dest)

    assert result.returncode != 0
    assert "pre-comit" in result.stderr


def test_the_merge_leaves_an_unrelated_project_alone(tmp_path: Path) -> None:
    """No fragments means no opinion, rather than an empty config overwriting one."""
    dest = tmp_path / "d"
    dest.mkdir()
    existing = dest / ".pre-commit-config.yaml"
    existing.write_text("repos: []\n")

    result = merge(dest)

    assert result.returncode == 0
    assert existing.read_text() == "repos: []\n"


# --- the real tools --------------------------------------------------------


def test_prek_accepts_the_generated_config(rendered: Path) -> None:
    """The config's own reader is the only authority on whether it is valid."""
    if shutil.which("prek") is None:
        pytest.skip("prek absent from PATH")

    result = subprocess.run(
        ["prek", "validate-config", ".pre-commit-config.yaml"],
        cwd=rendered,
        capture_output=True,
        text=True,
        check=False,
    )
    assert result.returncode == 0, result.stdout + result.stderr


def test_prek_installs_a_shim_for_every_declared_stage(rendered: Path) -> None:
    """The end of the chain: a stage in the config has to become a real git hook.

    `--git-dir` rather than a `core.hooksPath` override. prek declines to install while
    an ambient global hooksPath is set, which a machine-wide hook manager leaves behind,
    and it writes no shim while only printing a note. This machine has one set, so the
    test exercises exactly the case that used to fail silently.
    """
    if shutil.which("prek") is None:
        pytest.skip("prek absent from PATH")

    git_dir = subprocess.run(
        ["git", "rev-parse", "--absolute-git-dir"],
        cwd=rendered,
        capture_output=True,
        text=True,
        check=True,
    ).stdout.strip()

    result = subprocess.run(
        ["prek", "install", "--git-dir", git_dir],
        cwd=rendered,
        capture_output=True,
        text=True,
        check=False,
    )
    assert result.returncode == 0, result.stdout + result.stderr

    for stage in config(rendered)["default_install_hook_types"]:
        assert (rendered / ".git" / "hooks" / stage).is_file(), (
            f"no shim for {stage}, so that hook never fires"
        )


# --- the migrated git-action hooks -----------------------------------------

GIT_ACTION_IDS = {
    "normalize-close-keywords",
    "attribution-guard",
    "no-force-push-to-default",
}


def test_the_git_action_hooks_reach_the_merged_config(tmp_path: Path) -> None:
    """As PreToolUse hooks these fire only for an agent whose harness is configured. As prek
    entries committed to the repository they fire for every committer and survive an agent
    running without that config."""
    dest = tmp_path / "d"
    dest.mkdir()
    render("quality/hooks", dest, ANSWERS)

    config = yaml.safe_load((dest / ".pre-commit-config.yaml").read_text())
    ids = {hook["id"] for repo in config["repos"] for hook in repo["hooks"]}
    assert ids >= GIT_ACTION_IDS

    # A hook whose stage is absent from this list gets no shim, so it never fires.
    assert "commit-msg" in config["default_install_hook_types"]
    assert "pre-push" in config["default_install_hook_types"]


def test_the_vendored_scripts_carry_their_provenance(tmp_path: Path) -> None:
    """No checker enforces a copy across a repository boundary, so the header names the source
    and the re-sync command. This is the contract hooks-close-keywords documents."""
    dest = tmp_path / "d"
    dest.mkdir()
    render("quality/hooks", dest, ANSWERS)

    for name in ("commit-msg-rewrite.py", "close_keywords.py", "attribution_patterns.py"):
        body = (dest / "scripts" / name).read_text()
        assert "VENDORED from srobroek/agentic-packages" in body, f"{name} has no provenance"
        assert "cp <agentic-packages>" in body, f"{name} names no re-sync command"


def test_the_executable_hooks_arrive_executable(tmp_path: Path) -> None:
    """`language: script` runs the file directly, so a missing execute bit is a hook that
    never fires."""
    dest = tmp_path / "d"
    dest.mkdir()
    render("quality/hooks", dest, ANSWERS)

    for name in ("commit-msg-rewrite.py", "no_force_push.sh"):
        mode = (dest / "scripts" / name).stat().st_mode
        assert mode & 0o111, f"{name} is not executable"


def test_the_attribution_guard_is_advisory(tmp_path: Path) -> None:
    """It prints and exits 0. The message is trivially fixable, and a denied commit costs more
    than a nudge; the enforcing copy is the quality workflow's commits job over the whole
    range."""
    dest = tmp_path / "d"
    dest.mkdir()
    render("quality/hooks", dest, ANSWERS)

    message = dest / "msg"
    message.write_text("feat: add the thing\n\nCo-Authored-By: Claude <noreply@anthropic.com>\n")
    result = subprocess.run(
        [sys.executable, "scripts/attribution_guard.py", str(message)],
        cwd=dest,
        capture_output=True,
        text=True,
        check=False,
    )
    assert result.returncode == 0, "the guard must not block a commit"
    assert "AI attribution" in result.stderr, "it reported nothing"


def test_the_attribution_guard_ignores_ordinary_work(tmp_path: Path) -> None:
    """A commit about AI code is ordinary work. Every upstream pattern requires
    authorship-shaped context, and that scoping is why the patterns are vendored rather than
    rewritten."""
    dest = tmp_path / "d"
    dest.mkdir()
    render("quality/hooks", dest, ANSWERS)

    message = dest / "msg"
    message.write_text("fix: repair the claude client wrapper timeout\n")
    result = subprocess.run(
        [sys.executable, "scripts/attribution_guard.py", str(message)],
        cwd=dest,
        capture_output=True,
        text=True,
        check=False,
    )
    assert result.returncode == 0
    assert "AI attribution" not in result.stderr, "an ordinary commit was flagged"


def test_close_keywords_distributes_across_the_list(tmp_path: Path) -> None:
    """GitHub binds a closing keyword to the FIRST issue in a list, so `Closes #1, #2, #3`
    leaves #2 and #3 open."""
    dest = tmp_path / "d"
    dest.mkdir()
    render("quality/hooks", dest, ANSWERS)

    message = dest / "msg"
    message.write_text("fix: close them all\n\nCloses #1, #2, #3\n")
    result = subprocess.run(
        [sys.executable, "scripts/commit-msg-rewrite.py", str(message)],
        cwd=dest,
        capture_output=True,
        text=True,
        check=False,
    )
    assert result.returncode == 0, result.stderr
    assert "Closes #1, closes #2, closes #3" in message.read_text()


def test_the_force_push_guard_allows_a_fast_forward(tmp_path: Path) -> None:
    """A fast-forward has the remote commit as an ancestor. The force is not visible in the
    ref stream a pre-push hook receives, so the ancestry comparison is what detects it."""
    dest = tmp_path / "d"
    dest.mkdir()
    render("quality/hooks", dest, ANSWERS)

    subprocess.run(["git", "init", "-q", str(dest)], check=True)
    for key, value in (("user.email", "t@e.com"), ("user.name", "T")):
        subprocess.run(["git", "-C", str(dest), "config", key, value], check=True)
    (dest / "f").write_text("a\n")
    subprocess.run(["git", "-C", str(dest), "add", "-A"], check=True)
    subprocess.run(
        ["git", "-C", str(dest), "commit", "-qm", "one"], check=True, capture_output=True
    )
    first = subprocess.run(
        ["git", "-C", str(dest), "rev-parse", "HEAD"], capture_output=True, text=True, check=True
    ).stdout.strip()
    (dest / "f").write_text("a\nb\n")
    subprocess.run(["git", "-C", str(dest), "add", "-A"], check=True)
    subprocess.run(
        ["git", "-C", str(dest), "commit", "-qm", "two"], check=True, capture_output=True
    )
    second = subprocess.run(
        ["git", "-C", str(dest), "rev-parse", "HEAD"], capture_output=True, text=True, check=True
    ).stdout.strip()

    script = str(dest / "scripts" / "no_force_push.sh")

    forward = subprocess.run(
        ["bash", script],
        input=f"refs/heads/main {second} refs/heads/main {first}\n",
        cwd=dest,
        capture_output=True,
        text=True,
        check=False,
    )
    assert forward.returncode == 0, forward.stderr

    rewrite = subprocess.run(
        ["bash", script],
        input=f"refs/heads/main {first} refs/heads/main {second}\n",
        cwd=dest,
        capture_output=True,
        text=True,
        check=False,
    )
    assert rewrite.returncode == 1, "a history rewrite was allowed"
    assert "refusing to force push" in rewrite.stderr


def test_the_fragment_records_what_did_not_migrate(tmp_path: Path) -> None:
    """A pre-execution guard has no git event: by the time a hook runs, `reset --hard` has
    already discarded the work. Recording that beside the three that did migrate is what stops
    someone trying the other ten again."""
    dest = tmp_path / "d"
    dest.mkdir()
    render("quality/hooks", dest, ANSWERS)

    body = (dest / ".pre-commit.d" / "git-actions.yaml").read_text()
    for absent in ("hooks-quality", "hooks-bash-safety", "reset --hard", "clean -fd"):
        assert absent in body, f"the fragment does not say why {absent} stayed behind"
