#!/usr/bin/env python3
"""Fold .pre-commit.d/*.yaml into .pre-commit-config.yaml.

    merge_hooks.py <dest>

prek reads exactly one config file and has no include directive, so the fragment
convention needs this step. It also skips dot-prefixed directories when
discovering, which makes `.pre-commit.d/` invisible to it until this runs.

In a monorepo each member carries a real `.pre-commit-config.yaml` and prek's
workspace mode unions them, namespacing hooks `<dir>:<hook-id>`. This merge is for
the single-directory case, where two layers cannot both own the root file.

Deterministic: fragments fold in name order, so two runs produce the same bytes.
"""

from __future__ import annotations

import sys
from pathlib import Path

import yaml

HEADER = """\
# .pre-commit-config.yaml -- generated from .pre-commit.d/ by `just hooks-merge`.
#
# Do not edit this file. Add or change a fragment in .pre-commit.d/ and re-run the
# recipe; the whole file is rebuilt from its sources.
#
# `default_install_hook_types` has to name every stage the hooks below use, or
# `prek install` writes no shim for the missing one and that hook never fires.
"""

# Every stage a fragment may declare. `prek install` writes one shim per entry in
# default_install_hook_types, so a stage absent from that list is a hook that
# silently never runs.
STAGE_ORDER = (
    "pre-commit",
    "commit-msg",
    "prepare-commit-msg",
    "pre-merge-commit",
    "post-checkout",
    "post-merge",
    "post-commit",
    "post-rewrite",
    "pre-push",
    "pre-rebase",
)


def rev_key(rev: str) -> tuple:
    """Comparable sort key for a revision. Higher sorts newer.

    A parsed version outranks any unparseable string, so a sha never beats a tag.
    """
    stripped = rev.lstrip("v")
    try:
        return (1, tuple(int(part) for part in stripped.split(".")), "")
    except ValueError:
        return (0, (), rev)


def load(fragment: Path) -> dict:
    try:
        data = yaml.safe_load(fragment.read_text()) or {}
    except yaml.YAMLError as exc:
        raise SystemExit(f"{fragment.name} is not valid YAML: {exc}") from exc
    if not isinstance(data, dict):
        raise SystemExit(
            f"{fragment.name} must be a mapping with a top-level 'repos:' key, "
            f"got {type(data).__name__}"
        )
    return data


def merge(fragments: list[Path]) -> tuple[dict, list[str]]:
    repos: dict[str, dict] = {}
    excludes: list[str] = []
    warnings: list[str] = []

    for fragment in fragments:
        data = load(fragment)

        # Every fragment's exclude is kept. Taking only the first would silently
        # un-exclude whatever a later layer needed excluded.
        if data.get("exclude"):
            excludes.append(str(data["exclude"]))

        for entry in data.get("repos", []):
            url = entry.get("repo", "")
            if not url:
                continue
            rev = entry.get("rev", "")
            hooks = entry.get("hooks", [])

            if url not in repos:
                repos[url] = {"rev": rev, "hooks": list(hooks), "source": fragment.name}
                continue

            existing = repos[url]
            if rev and existing["rev"] and rev != existing["rev"]:
                winner = max(existing["rev"], rev, key=rev_key)
                warnings.append(
                    f"{url} pinned {existing['rev']} by {existing['source']} and "
                    f"{rev} by {fragment.name}; using {winner}"
                )
                existing["rev"] = winner

            seen = {hook.get("id") for hook in existing["hooks"]}
            for hook in hooks:
                if hook.get("id") in seen:
                    warnings.append(
                        f"{fragment.name} redefines hook {hook.get('id')!r}, which "
                        f"{existing['source']} already declared; keeping the first"
                    )
                    continue
                existing["hooks"].append(hook)
                seen.add(hook.get("id"))

    config: dict = {}
    if excludes:
        # Alternation rather than a single pattern, so two layers' excludes compose.
        config["exclude"] = "|".join(f"(?:{pattern})" for pattern in excludes)

    stages = {
        stage
        for repo in repos.values()
        for hook in repo["hooks"]
        for stage in hook.get("stages", ["pre-commit"])
    }
    # Ordered by when git fires them rather than alphabetically, and filtered
    # through STAGE_ORDER so an unknown stage surfaces instead of being written out.
    unknown = stages - set(STAGE_ORDER)
    if unknown:
        raise SystemExit(f"unknown hook stage(s): {', '.join(sorted(unknown))}")
    config["default_install_hook_types"] = [s for s in STAGE_ORDER if s in stages]

    config["repos"] = [
        {
            "repo": url,
            **({"rev": repos[url]["rev"]} if repos[url]["rev"] else {}),
            "hooks": repos[url]["hooks"],
        }
        for url in sorted(repos)
    ]
    return config, warnings


def main() -> int:
    if len(sys.argv) < 2:
        print(__doc__, file=sys.stderr)
        return 2

    dest = Path(sys.argv[1])
    directory = dest / ".pre-commit.d"
    fragments = sorted(directory.glob("*.yaml")) if directory.is_dir() else []
    if not fragments:
        print("no .pre-commit.d fragments, leaving .pre-commit-config.yaml alone")
        return 0

    config, warnings = merge(fragments)
    for warning in warnings:
        print(f"warning: {warning}", file=sys.stderr)

    (dest / ".pre-commit-config.yaml").write_text(
        HEADER
        + yaml.dump(
            config,
            default_flow_style=False,
            sort_keys=False,
            # A wrapped `entry:` still folds back to the same command, but it reads
            # as a broken shell line and every later edit rewraps the block, which
            # makes the diff noise rather than the change.
            width=10_000,
        )
    )
    stages = ", ".join(config["default_install_hook_types"])
    print(f"merged {len(fragments)} fragment(s) into .pre-commit-config.yaml ({stages})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
