name: Setup TypeScript
description: Install bun and the locked dependencies.

runs:
  using: composite
  steps:
    - uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76 # v2.0.2
      with:
        bun-version: latest

    - name: Install the locked dependencies
      shell: bash
      run: bun install --frozen-lockfile
