#!/usr/bin/env python3
"""Build .gitignore from gitnr templates plus every .gitignore.d fragment.

    fold_gitignore.py <dest> [gitnr-sources]

gitnr covers the bulk per language. A fragment carries what gitnr cannot express:
`Cargo.lock` ignored for a library but committed for a binary, `vendor/` under Go
vendor mode, or a tool's output path.

Always ignored regardless of language, because a layer or a hook writes them:
the repomix pack, generated skill directories, and the beads Dolt database.

Idempotent: the whole file is rebuilt from its sources every run.
"""

from __future__ import annotations

import shutil
import subprocess
import sys
from pathlib import Path

GITNR_TIMEOUT_SECONDS = 120

# Written by a hook or a layer rather than by a person, and large.
ALWAYS = """# Generated by a tool in this repository, never committed.
repomix.xml
repomix-*.xml
.claude/skills/repomix-*/

# Local state
.DS_Store
*.log
"""


def gitnr_output(sources: list[str]) -> str:
    if not sources:
        return ""
    if shutil.which("gitnr") is None:
        print("gitnr absent from PATH, skipping its templates", file=sys.stderr)
        return ""
    result = subprocess.run(
        ["gitnr", "create", *sources],
        capture_output=True,
        text=True,
        check=False,
        timeout=GITNR_TIMEOUT_SECONDS,
    )
    if result.returncode != 0:
        detail = result.stderr.strip() or f"exit {result.returncode}"
        raise SystemExit(f"gitnr failed for {' '.join(sources)}: {detail}")
    return result.stdout


def fragments(dest: Path) -> str:
    """Fold .gitignore.d/* in name order so two runs produce the same file."""
    directory = dest / ".gitignore.d"
    if not directory.is_dir():
        return ""
    blocks = []
    for fragment in sorted(directory.iterdir()):
        if not fragment.is_file() or fragment.name.startswith("."):
            continue
        body = fragment.read_text().strip()
        if not body:
            continue
        # A fragment may open with its own comment; do not add a second one.
        header = "" if body.startswith("#") else f"# {fragment.name}\n"
        blocks.append(f"{header}{body}\n")
    return "\n".join(blocks)


def main() -> int:
    if len(sys.argv) < 2:
        print(__doc__, file=sys.stderr)
        return 2

    dest = Path(sys.argv[1])
    sources = sys.argv[2].split() if len(sys.argv) > 2 and sys.argv[2].strip() else []

    parts = [ALWAYS]

    fragment_text = fragments(dest)
    if fragment_text:
        parts.append(fragment_text)

    remote = gitnr_output(sources)
    if remote:
        parts.append(remote)

    (dest / ".gitignore").write_text("\n".join(part.rstrip() + "\n" for part in parts if part))

    counted = len(list((dest / ".gitignore.d").iterdir())) if (dest / ".gitignore.d").is_dir() else 0
    print(f".gitignore written from {len(sources)} gitnr source(s) and {counted} fragment(s)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
