#!/usr/bin/env python3
"""Regenerate docs/INDEX.md from recipes/.

    index.py [--check]

`--check` regenerates in memory and exits 1 when the file on disk differs,
naming the command that fixes it.
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
RECIPES = REPO_ROOT / "recipes"
INDEX = REPO_ROOT / "docs" / "INDEX.md"

HEADER = """# Recipe index

Generated by `just index`. Every recipe under `recipes/`, with the questions it
asks and the files it writes.

Design lives in `recipes.md`; this file is the inventory.
"""


def recipes(files: set[Path]) -> list[tuple[str, Path]]:
    """Every recipe git tracks a copier.yml for. See `tracked` for why git rather than the
    filesystem: an uncommitted recipe in one working tree would otherwise land in the index and
    read as stale everywhere else."""
    found = []
    for config in sorted(files):
        if config.name != "copier.yml" or config.parent.parent.parent != RECIPES:
            continue
        found.append((str(config.parent.relative_to(RECIPES)), config.parent))
    return found


def questions(config: dict) -> list[tuple[str, str, str]]:
    rows = []
    for key, value in config.items():
        if key.startswith("_") or not isinstance(value, dict):
            continue
        kind = value.get("type", "str")
        default = value.get("default", "")
        if "choices" in value:
            choices = value["choices"]
            names = list(choices) if isinstance(choices, list) else list(choices.keys())
            kind = " | ".join(f"`{c}`" for c in names)
        rows.append((key, str(kind), f"`{default}`" if default != "" else ""))
    return rows


def tracked() -> set[Path]:
    """Every file git tracks, as absolute paths.

    The index is derived from what the repository contains, not from what happens to sit in a
    working tree. Walking the filesystem put two `__pycache__/*.pyc` paths from a local
    bytecode cache into the committed index, which then read as stale on every CI run: the
    runner has no such files. `.gitignore` already covers them, so git is the authority.
    """
    result = subprocess.run(
        ["git", "-C", str(REPO_ROOT), "ls-files", "-z", "--", "recipes"],
        capture_output=True,
        text=True,
        check=True,
    )
    return {REPO_ROOT / entry for entry in result.stdout.split("\0") if entry}


def rendered_paths(path: Path, files: set[Path]) -> list[str]:
    subdir = path / "template"
    if not subdir.is_dir():
        return []
    out = []
    for item in sorted(files):
        if subdir not in item.parents:
            continue
        rel = str(item.relative_to(subdir))
        if rel.startswith("{{ _copier_conf.answers_file }}"):
            continue
        out.append(rel.removesuffix(".jinja"))
    return out


def build() -> str:
    parts = [HEADER]
    files = tracked()
    found = recipes(files)

    parts.append("\n## Recipes\n")
    parts.append("| Recipe | Questions | Files |")
    parts.append("|---|---|---|")
    for name, path in found:
        config = yaml.safe_load((path / "copier.yml").read_text()) or {}
        written = len(rendered_paths(path, files))
        parts.append(f"| `{name}` | {len(questions(config))} | {written} |")

    for name, path in found:
        config = yaml.safe_load((path / "copier.yml").read_text()) or {}
        parts.append(f"\n## `{name}`\n")

        meta = config.get("_scaffold") or {}
        if isinstance(meta, dict):
            if meta.get("summary"):
                parts.append(f"{meta['summary']}\n")
            if meta.get("requires_bin"):
                needs = ", ".join(f"`{b}`" for b in meta["requires_bin"])
                parts.append(f"Requires {needs} on `PATH`.\n")

        rows = questions(config)
        if rows:
            parts.append("| Question | Type | Default |")
            parts.append("|---|---|---|")
            for key, kind, default in rows:
                parts.append(f"| `{key}` | {kind} | {default} |")
            parts.append("")

        paths = rendered_paths(path, files)
        if paths:
            parts.append("Writes:\n")
            parts.append("```")
            parts.extend(paths)
            parts.append("```")

    return "\n".join(parts).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(prog="index.py", description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    content = build()

    if args.check:
        current = INDEX.read_text() if INDEX.is_file() else ""
        if current != content:
            print(f"stale: {INDEX.relative_to(REPO_ROOT)}", file=sys.stderr)
            print("fix with: just index", file=sys.stderr)
            return 1
        return 0

    INDEX.parent.mkdir(parents=True, exist_ok=True)
    INDEX.write_text(content)
    print(f"wrote {INDEX.relative_to(REPO_ROOT)} ({len(recipes(tracked()))} recipes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
