#!/usr/bin/env python3
"""Regenerate docs/INDEX.md from templates/.

    index.py [--check]

`--check` regenerates in memory and exits 1 when the file on disk differs,
naming the command that fixes it.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
TEMPLATES = REPO_ROOT / "templates"
INDEX = REPO_ROOT / "docs" / "INDEX.md"

HEADER = """# Layer index

Generated by `just index`. Every layer under `templates/`, with the questions it
asks and the files it writes.

Design lives in `layers.md`; this file is the inventory.
"""


def layers() -> list[tuple[str, Path]]:
    found = []
    for config in sorted(TEMPLATES.rglob("copier.yml")):
        found.append((str(config.parent.relative_to(TEMPLATES)), config.parent))
    return found


def questions(config: dict) -> list[tuple[str, str, str]]:
    rows = []
    for key, value in config.items():
        if key.startswith("_") or not isinstance(value, dict):
            continue
        kind = value.get("type", "str")
        default = value.get("default", "")
        if "choices" in value:
            choices = value["choices"]
            names = list(choices) if isinstance(choices, list) else list(choices.keys())
            kind = " | ".join(f"`{c}`" for c in names)
        rows.append((key, str(kind), f"`{default}`" if default != "" else ""))
    return rows


def rendered_paths(path: Path) -> list[str]:
    subdir = path / "template"
    if not subdir.is_dir():
        return []
    out = []
    for item in sorted(subdir.rglob("*")):
        if item.is_file():
            rel = str(item.relative_to(subdir))
            if rel.startswith("{{ _copier_conf.answers_file }}"):
                continue
            out.append(rel.removesuffix(".jinja"))
    return out


def build() -> str:
    parts = [HEADER]
    found = layers()

    parts.append("\n## Layers\n")
    parts.append("| Layer | Questions | Files |")
    parts.append("|---|---|---|")
    for name, path in found:
        config = yaml.safe_load((path / "copier.yml").read_text()) or {}
        parts.append(f"| `{name}` | {len(questions(config))} | {len(rendered_paths(path))} |")

    for name, path in found:
        config = yaml.safe_load((path / "copier.yml").read_text()) or {}
        parts.append(f"\n## `{name}`\n")

        meta = config.get("_scaffold") or {}
        if isinstance(meta, dict):
            if meta.get("summary"):
                parts.append(f"{meta['summary']}\n")
            if meta.get("requires_bin"):
                needs = ", ".join(f"`{b}`" for b in meta["requires_bin"])
                parts.append(f"Requires {needs} on `PATH`.\n")

        rows = questions(config)
        if rows:
            parts.append("| Question | Type | Default |")
            parts.append("|---|---|---|")
            for key, kind, default in rows:
                parts.append(f"| `{key}` | {kind} | {default} |")
            parts.append("")

        paths = rendered_paths(path)
        if paths:
            parts.append("Writes:\n")
            parts.append("```")
            parts.extend(paths)
            parts.append("```")

    return "\n".join(parts).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(prog="index.py", description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    content = build()

    if args.check:
        current = INDEX.read_text() if INDEX.is_file() else ""
        if current != content:
            print(f"stale: {INDEX.relative_to(REPO_ROOT)}", file=sys.stderr)
            print("fix with: just index", file=sys.stderr)
            return 1
        return 0

    INDEX.parent.mkdir(parents=True, exist_ok=True)
    INDEX.write_text(content)
    print(f"wrote {INDEX.relative_to(REPO_ROOT)} ({len(layers())} layers)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
