#!/usr/bin/env python3
"""Rebuild .github/workflows/ci.yml from the reusable workflows beside it.

    gen_caller.py [<dest>] [--default-branch <name>] [--keep-hand-owned]

A reusable workflow does not run itself: GitHub needs a caller wiring `needs:` and the path
filters between them. Which workflows exist depends on which layers rendered, so the caller
is derived from the directory rather than written by hand, and `just ci-sync` rebuilds it
when a layer is added.

The whole file is rewritten each run, unlike the marker blocks the other generators here
preserve. Every line of a caller is derived from the tree, so there is no hand-written half
to keep. A ci.yml whose first line is not the marker is therefore somebody else's file and
is refused rather than replaced: a repository needing a job this script cannot derive -- a
monorepo passing `working-directory` per member, a container build, a tofu plan -- takes the
file over by dropping that line.

The graph it emits:

    changes ─┬─> lint-<lang> ─┐
             └─> test-<lang> ─┤
                              ├──> gate
    quality ──────────────────┤
    security ─────────────────┘

`changes` evaluates every filter once and each language job reads its own key. The filtering
has to sit on the jobs: a workflow gated at `on.push.paths` does not run at all for an
unrelated change, and `gate` is the only required status check, so one that never runs leaves
the pull request unmergeable forever. A filtered job reports `skipped`, which the gate counts
as a pass.

`quality` and `security` wait for nothing. Each reads its own fragment directory and builds
its own matrix, so neither takes a language input nor has a filter to read.

Only `changes` and `gate` receive an input. Every lint and test workflow declares its inputs
optional with a default its own layer chose, so a caller passing one would overwrite a
recorded answer with a guess.

Deterministic: languages sort by name, so two runs write the same bytes.

Exit codes:
    0  written, nothing here to wire, or hand-owned under --keep-hand-owned
    1  a language whose paths this script does not know
    3  ci.yml is hand-owned, so nothing was written
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

WORKFLOWS = ".github/workflows"
CALLER = f"{WORKFLOWS}/ci.yml"

# The first line of the generated file, and this script's claim to it.
MARKER = "# Generated by scripts/gen_caller.py -- edit the wc-* workflows, not this file"

# The host layer's own four. Wired by name rather than discovered: each takes a different
# input, and only one needs a permission the caller has to grant.
HOST = ("wc-changes.yml", "wc-gate.yml", "wc-quality.yml", "wc-security.yml")

# What a language's jobs read, so a change anywhere in its set re-runs them. Grounded in the
# files each lang/* layer renders and the lockfiles its .github/security.d fragment names.
# The layers ship no path fragment, so a language reaching CI is what adds an entry here,
# and one arriving without an entry is refused rather than guessed at.
FILTERS: dict[str, tuple[str, ...]] = {
    "api": ("openapi.yaml", ".vacuum.yaml"),
    "go": ("**/*.go", "**/go.mod", "**/go.sum", ".golangci.yml"),
    "python": ("**/*.py", "**/pyproject.toml", "**/uv.lock", "ruff.toml", "pytest.ini"),
    "rust": (
        "**/*.rs",
        "**/Cargo.toml",
        "**/Cargo.lock",
        "rust-toolchain.toml",
        "clippy.toml",
        "rustfmt.toml",
        "deny.toml",
    ),
    # `tofu` rather than `terraform`: the key is the workflow's own suffix, and the workflow
    # is named for the binary that runs.
    "tofu": ("**/*.tf", "**/*.tfvars", "**/*.tfbackend", ".tflint.hcl"),
    "ts": (
        "**/*.ts",
        "**/*.tsx",
        "**/package.json",
        "**/tsconfig.json",
        "**/bun.lock",
        "**/package-lock.json",
        "**/pnpm-lock.yaml",
        "biome.json",
        ".oxlintrc.json",
    ),
}

HEADER = f"""\
{MARKER}
#
# The caller. A reusable workflow does not run itself, and which ones exist depends on which
# layers rendered, so `just ci-sync` rebuilds this file from {WORKFLOWS}/.
#
# Path filtering sits on the jobs, never on `on.push.paths`. A workflow gated at the `on:`
# level does not run at all for an unrelated change, and `gate` is the only required status
# check, so one that never runs leaves the pull request unmergeable. A job the filter skipped
# reports `skipped`, which the gate counts as a pass."""

SETTINGS = """\
# The floor every called workflow inherits. Only `security` needs more than this.
permissions:
  contents: read

# A second push to the same ref supersedes the first. Two refs never cancel each other.
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true"""

QUALITY = f"""\
  # No language input: it reads .github/quality.d/ and builds its own matrix. Nothing to
  # filter on either, since its own jobs skip when no fragment supplies one.
  quality:
    uses: ./{WORKFLOWS}/wc-quality.yml"""

SECURITY = f"""\
  security:
    # The scans upload SARIF, and a called workflow cannot hold more than its caller granted.
    # Naming permissions replaces the default set rather than adding to it, so `contents:
    # read` is repeated here.
    permissions:
      contents: read
      security-events: write
    uses: ./{WORKFLOWS}/wc-security.yml"""

# The branch the push trigger names, read back out of the file being replaced. Every other
# layer bakes its own `default_branch` answer at render time; this file is written after the
# render, so the copier task passes it and a later bare `just ci-sync` recovers it. Without
# the read-back a re-sync would quietly retrigger a `trunk` repository on `main`.
PUSH_BRANCH = re.compile(r"^    branches: \[([^\]]+)\]$", re.M)


def jobs_by_language(workflows: Path) -> dict[str, list[str]]:
    """{language: kinds} for every wc-<kind>-<language>.yml, in emission order.

    lint and test are counted separately rather than as a pair: lang/api contributes a lint
    workflow and no test one, and requiring a pair would drop it from CI entirely.
    """
    found: dict[str, set[str]] = {}
    for path in workflows.glob("wc-*.yml"):
        _, _, rest = path.stem.partition("-")
        kind, _, language = rest.partition("-")
        if kind in ("lint", "test") and language:
            found.setdefault(language, set()).add(kind)
    return {
        language: [kind for kind in ("lint", "test") if kind in kinds]
        for language, kinds in sorted(found.items())
    }


def filter_paths(language: str) -> tuple[str, ...]:
    """Every path whose change has to re-run this language's jobs.

    The workflow and the setup action are in the set because a change to either changes what
    the job does, and this file is in it because the pull request that wires a language has
    to exercise the jobs it just added.
    """
    if language not in FILTERS:
        raise SystemExit(
            f"wc-*-{language}.yml contributes jobs for {language!r}, which has no entry in "
            "FILTERS in scripts/gen_caller.py. Add its paths: an unfiltered job runs on every "
            "change, and a guessed filter skips a change it should have tested."
        )
    return (
        *FILTERS[language],
        f"{WORKFLOWS}/wc-*-{language}.yml",
        f".github/actions/setup-{language}/**",
        CALLER,
    )


def unwired(workflows: Path, languages: dict[str, list[str]]) -> list[str]:
    """The reusable workflows this script leaves alone, so the file can say so."""
    wired = {f"wc-{kind}-{language}.yml" for language, kinds in languages.items() for kind in kinds}
    return sorted(
        path.name
        for path in workflows.glob("wc-*.yml")
        if path.name not in wired and path.name not in HOST
    )


def header(names: list[str]) -> str:
    """The comment block, naming any reusable workflow the caller deliberately skips.

    Named rather than silently left out: a reader who can see the workflow needs to know
    why nothing calls it, and what to do about it.
    """
    if not names:
        return HEADER
    listed = "\n".join(f"#   {name}" for name in names)
    return (
        f"{HEADER}\n"
        "#\n"
        "# Not wired here:\n"
        f"{listed}\n"
        "#\n"
        "# Each needs a caller decision this script cannot derive from the tree -- a role ARN,\n"
        "# a registry push only on the default branch, a permission grant. A repository using\n"
        "# one owns its caller: drop the marker line above, after which this script refuses the\n"
        "# file rather than rewriting it."
    )


def job_names(languages: dict[str, list[str]]) -> list[str]:
    """Every job the caller emits before the gate, which is what the gate needs."""
    names = ["changes"] if languages else []
    names += [f"{kind}-{language}" for language, kinds in languages.items() for kind in kinds]
    return [*names, "quality", "security"]


def changes_job(languages: dict[str, list[str]]) -> str:
    lines = [
        "  # One filter evaluation for the whole run, output as the JSON array of keys that",
        "  # matched. Each set names the language's sources, the manifests and lockfiles that",
        "  # decide what is built, the workflow that runs it, and this file: the pull request",
        "  # wiring a language has to exercise the jobs it adds.",
        "  changes:",
        f"    uses: ./{WORKFLOWS}/wc-changes.yml",
        "    with:",
        "      filters: |",
    ]
    for language in languages:
        lines.append(f"        {language}:")
        lines += [f"          - '{path}'" for path in filter_paths(language)]
    return "\n".join(lines)


def language_job(kind: str, language: str) -> str:
    return "\n".join(
        [
            f"  {kind}-{language}:",
            "    needs: changes",
            f"    if: contains(fromJSON(needs.changes.outputs.changes), '{language}')",
            f"    uses: ./{WORKFLOWS}/wc-{kind}-{language}.yml",
        ]
    )


def gate_job(needed: list[str]) -> str:
    return "\n".join(
        [
            "  # The only required status check. It judges every other job's result, so a job",
            "  # added above is covered without touching branch protection.",
            "  gate:",
            "    needs:",
            *(f"      - {name}" for name in needed),
            "    # Without always() the gate is skipped whenever anything it needs was skipped",
            "    # or failed, and a required check that never reports blocks the pull request.",
            "    if: always()",
            f"    uses: ./{WORKFLOWS}/wc-gate.yml",
            "    with:",
            "      needs: ${{ toJSON(needs) }}",
        ]
    )


def caller(languages: dict[str, list[str]], branch: str, note: list[str]) -> str:
    """The whole file."""
    top = "\n\n".join(
        [
            header(note),
            "name: CI",
            f"on:\n  push:\n    branches: [{branch}]\n  pull_request:",
            SETTINGS,
            "jobs:",
        ]
    )
    jobs = [changes_job(languages)] if languages else []
    for language, kinds in languages.items():
        jobs += [language_job(kind, language) for kind in kinds]
    jobs += [QUALITY, SECURITY, gate_job(job_names(languages))]
    return f"{top}\n" + "\n\n".join(jobs) + "\n"


def push_branch(existing: str, override: str | None) -> str:
    if override:
        return override
    found = PUSH_BRANCH.search(existing)
    return found.group(1) if found else "main"


def main() -> int:
    parser = argparse.ArgumentParser(
        prog="gen_caller.py",
        description="Rebuild .github/workflows/ci.yml from the reusable workflows beside it.",
    )
    parser.add_argument("dest", nargs="?", default=Path("."), type=Path, help="repository root")
    parser.add_argument(
        "--default-branch",
        help="branch the push trigger names; the value already in ci.yml otherwise, then main",
    )
    parser.add_argument(
        "--keep-hand-owned",
        action="store_true",
        help="exit 0 rather than 3 on a hand-owned ci.yml, for a render that must not fail",
    )
    args = parser.parse_args()

    workflows = args.dest / WORKFLOWS
    if not (workflows / "wc-gate.yml").is_file():
        # Nothing to call. A caller naming a workflow that is not there fails at the run
        # rather than at lint time, so writing one would be worse than writing nothing.
        print(f"no {WORKFLOWS}/wc-gate.yml here, so there is no caller to write")
        return 0

    path = args.dest / CALLER
    existing = path.read_text() if path.is_file() else ""
    if existing and not existing.startswith(MARKER):
        report = f"{CALLER} has no generator marker, so it is hand-owned"
        if args.keep_hand_owned:
            print(f"{report}; left alone")
            return 0
        print(
            f"{report}; refusing to overwrite it. Delete the file to hand the caller back "
            "to this script.",
            file=sys.stderr,
        )
        return 3

    languages = jobs_by_language(workflows)
    branch = push_branch(existing, args.default_branch)
    body = caller(languages, branch, unwired(workflows, languages))
    if body != existing:
        path.write_text(body)

    print(f"{CALLER}: {', '.join([*job_names(languages), 'gate'])}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
